# https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.MLFlowLogger.html
_target_: pytorch_lightning.loggers.TensorBoardLogger

save_dir: tb
name: ${experiment_name}