# @package dataset

# _target_: src.dataset.celeba

train_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  batch_size: 32
  num_workers: 4
  pin_memory: True

train_dataset:
  _target_: src.dataset.celeba.TrainDataset
  img_size: 64
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]

val_dataloader:
  _target_:   

test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ???
  dataset_class:
    _target_: src.dataset.celeba.TestDataset
    img_size: 64
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
  batch_size: 32
  num_workers: 4
  pin_memory: True