# @package optimizer_d
# https://pytorch.org/docs/stable/generated/torch.optim.Adam.html

_target_: torch.optim.Adam
params: ???
lr: 0.0002
betas: [0.5, 0.999]
eps: 1e-08
weight_decay: 0
amsgrad: False